name: Build and Deploy to Render via Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create .env from github secrets
        run: |
          cat > .env <<EOF
          AI_CHAT_API_KEY=${{secrets.AI_CHAT_API_KEY}}
          AI_CHAT_API_URL=${{secrets.AI_CHAT_API_URL}}
          AI_CHAT_MODEL=${{secrets.AI_CHAT_MODEL}}
          EOF

      - name: Run Tests
        run: mvn -B test

      ### Build moved to DockerFile
      #- name: Build with Maven
      #  run: mvn clean package -DskipTests

      - name: Login to GHCR
        run: echo "${{secrets.CR_PAT}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Build docker image
        run: |
          docker build -t ghcr.io/xyahik/steplang-app:latest .
          docker push ghcr.io/xyahik/steplang-app:latest

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{secrets.RENDER_SERVICE_ID}}
          api_key: ${{secrets.RENDER_API_KEY}}
          wait_deploy: true
